// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCir6sjoSM9n48nN18DIpeDdA-kcCoJTXg',
    appId: '1:630522184803:android:c92a663e50dd63ab736456',
    messagingSenderId: '630522184803',
    projectId: 'note-ease-ec2ab',
    databaseURL: 'https://note-ease-ec2ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-ease-ec2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-S8VzU5SJi9NhkpY_QQwyIJWB9kDduM',
    appId: '1:630522184803:ios:268c41de1a041ec6736456',
    messagingSenderId: '630522184803',
    projectId: 'note-ease-ec2ab',
    databaseURL: 'https://note-ease-ec2ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-ease-ec2ab.firebasestorage.app',
    iosBundleId: 'com.example.moneyEase',
  );
}
